project_id = "fstxrxojxnziuqqceobd"

[functions.chat]
verify_jwt = false

[functions.check-subscription-expiry]
verify_jwt = false

[functions.realtime-data]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-push]
verify_jwt = false
